services:
  _defaults:
    autowire:       true
    autoconfigure:  true
    public:         true

##### Services #####
  Austral\EntityBundle\Services\InitialiseBundleEntities: "@austral.entity.initialise-bundle"
  austral.entity.initialise-bundle:
    class:        Austral\EntityBundle\Services\InitialiseBundleEntities
    arguments:    ["@service_container"]

  Austral\EntityBundle\EntityAnnotation\EntitiesAnnotations:  "@austral.entity.entities-annotations"
  austral.entity.entities-annotations:
    class:        Austral\EntityBundle\EntityAnnotation\EntitiesAnnotations
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@annotation_reader"
      - "@austral.tools.debug"

  Austral\EntityBundle\Mapping\Mapping: "@austral.entity.mapping"
  austral.entity.mapping:
    class:        Austral\EntityBundle\Mapping\Mapping
    arguments:
      - "@austral.entity_manager"
      - "@austral.tools.debug"

##### Austral Event Subscriber
  Austral\EntityBundle\EventSubscriber\EntityManagerEventSubscriber:  "@austral.entity.manager.event_subscriber"
  austral.entity.manager.event_subscriber:
    class:        Austral\EntityBundle\EventSubscriber\EntityManagerEventSubscriber
    tags:
      - { name: kernel.event_subscriber}

  Austral\EntityBundle\EventSubscriber\EntityMappingEventSubscriber:  "@austral.entity.mapping.event_subscriber"
  austral.entity.mapping.event_subscriber:
    class:        Austral\EntityBundle\EventSubscriber\EntityMappingEventSubscriber
    tags:
      - { name: kernel.event_subscriber }

  Austral\EntityBundle\EventSubscriber\QueryBuilderEventSubscriber: "@austral.entity.query_builder.event_subscriber"
  austral.entity.query_builder.event_subscriber:
    class:        Austral\EntityBundle\EventSubscriber\QueryBuilderEventSubscriber
    tags:
      - { name: kernel.event_subscriber }

##### Austral Entity Manager
  Austral\EntityBundle\EntityManager\EntityManager: "@austral.entity_manager"
  austral.entity_manager:
    class:        Austral\EntityBundle\EntityManager\EntityManager
    arguments:    [ "@doctrine.orm.entity_manager",  "@event_dispatcher" ]

##### Annotation Listener Kernel
  Austral\EntityBundle\Listener\EntityMappingListener:  "@austral.entity.mapping.listener"
  austral.entity.mapping.listener:
    class:          Austral\EntityBundle\Listener\EntityMappingListener
    arguments:
      - "@austral.entity.mapping"
      - "@austral.entity.entities-annotations"
      - "@event_dispatcher"
      - "@austral.tools.debug"
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: initEntityAnnotations, priority: 0 }